# Generated by Django 4.1.7 on 2024-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
