# Generated by Django 4.1.7 on 2024-07-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='terrains',
            field=models.ManyToManyField(related_name='planets', to='planets.terrain'),
        ),
    ]
