# Generated by Django 4.1.7 on 2024-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0006_climate'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='climates',
            field=models.ManyToManyField(related_name='planets', to='planets.climate'),
        ),
    ]
